### PR TITLE
Test PR

### PR DESCRIPTION
**Pull request by svlandeg**
PR that isn't to be merged - only serving to test the explosion bot.

### CODE REVIEW

**Comment by svlandeg** [comment]
@explosion-bot please test_external

**Comment by svlandeg** [comment]
@explosion-bot please test_external

**Comment by svlandeg** [comment]
@explosion-bot please test_gpu

**Comment by svlandeg** [comment]
@explosion-bot please info

**Comment by rmitsch** [comment]
@explosion-bot please info

**Comment by rmitsch** [comment]
@explosion-bot please test_llm_external

**Comment by rmitsch** [comment]
@explosion-bot please test_gpu_external

**Comment by rmitsch** [comment]
@explosion-bot please test_gpu

**Comment by rmitsch** [comment]
please test gpu

**Comment by rmitsch** [comment]
please test external

**Comment by rmitsch** [comment]
please test external

**Comment by rmitsch** [comment]
please test_external

**Comment by rmitsch** [comment]
please test external

**Pull request closed without merging**
