### PR TITLE
clean up assemble to call assemble_from_config

### PR DESCRIPTION
**Pull request by kabirkhan**
## Description

We have some duplicated code between `assemble` and `assemble_from_config`. Seems nice consolidate this logic and have `assemble` just load config and then call into `assemble_from_config`. Also adding basic docstrings

### Types of change

Refactor

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran all tests in `tests` and `usage_examples/tests`, and all new and existing tests passed. This includes
  - all external tests (i. e. `pytest` ran with `--external`)
  - all tests requiring a GPU
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by rmitsch** [comment]
Is this ready to be reviewed?

**Review by bdura — APPROVED** [review]

**Comment by kabirkhan** [comment]
@rmitsch yep it is. Just saw this while working on a different change and figured I'd fix it. Just forgot to request any reviewers.

**Comment by svlandeg** [comment]
> @rmitsch yep it is. Just saw this while working on a different change and figured I'd fix it. Just forgot to request any reviewers.

No need to request reviewers - for the OS repo's we just use the internal board so there's always at most one person assigned and we avoid duplicate/unclear assignments ;-)

**Review by svlandeg — COMMENTED** [review]
Looks good! This doesn't look like a breaking change to me, so I think we could have this on `master` (next bugfix release) instead of `develop` (next minor release).

**Comment by kabirkhan** [comment]
Ok sounds good. Swapped the branch to point at `main` instead of `develop`.

**Pull request merged**
