### PR TITLE
Add support for Azure OpenAI, Palm, Replicate, Sagemaker (100+LLMs) - using litellm

### PR DESCRIPTION
**Pull request by ishaan-jaff**
## Description

This PR adds support for the above mentioned LLMs using LiteLLM https://github.com/BerriAI/litellm/ 
Example
```python
from litellm import completion

## set ENV variables
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion("command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

## Checklist

- [ ] I confirm that I have the right to submit this contribution under the project's MIT license.
- [ ] I ran all tests in `tests` and `usage_examples/tests`, and all new and existing tests passed. This includes
  - all external tests (i. e. `pytest` ran with `--external`)
  - all tests requiring a GPU (i. e. `pytest` ran with `--gpu`)
- [ ] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
I noticed this repo has mutliple files for HF, OpenAI, Cohere, Anthropic etc. This PR allows for:
* Adding support for all the LiteLLM supported LLMs 
* Simplifying maintaining/adding new LLMs for spacy-llm

**Comment by ishaan-jaff** [comment]
@rmitsch can you take a look at this PR when you get the chance? 

Happy to add more docs/testing if this initial commit looks good

**Comment by rmitsch** [comment]
Hi @ishaan-jaff, thanks for this PR! Could you elaborate on which functionality you think is missing in `spacy-llm` that this PR would add? I'm not too familiar with `litellm`, so I couldn't say how it would complement the already integrated `langchain`.

**Comment by svlandeg** [comment]
Closing this PR for now as we're uncertain about the added value of having `litellm` as a dependency on top of the `langchain` integration we've already got. We really do appreciate your contribution though, and are always happy to discuss more in the future!

**Pull request closed without merging**
